### PR TITLE
Bump to 1.2.2, rerender with conda-smithy 2.4.4

### PR DESCRIPTION
**Pull request by bollwyvl**
This updates to `deap` 1.2.2, runs the test suite with `nose`, includes the license file, and all manner of other good things. Thanks @TiemenSch for pointing out availability on #4!

I think it's still okay to not set `numpy x.x`, as it doesn't look like the compiled bits include any numpy headers, hooray!

### CODE REVIEW

**Comment by bollwyvl** [comment]
Builds are looking good! Once they finish, I'll fix the lint and (hopefully) merge later today! 🤞

**Comment by TiemenSch** [comment]
Great! Thanks so much for picking this up so quickly 👍

**Comment by bollwyvl** [comment]
Builds 💚 ! @TiemenSch, would you be interested in joining our merry band of maintainers?

**Comment by bollwyvl** [comment]
Well fixing the lint so that we get back in the queue. Make a PR with your own name in `maintainers` if you are so inclined!

**Comment by bollwyvl** [comment]
Take that lint!

**Comment by TiemenSch** [comment]
What would you expect from me if I were to become a maintainer (:?

**Comment by bollwyvl** [comment]
@TiemenSch the `conda-forge` team has tried to make maintainership as [easy as possible](https://conda-forge.org/docs/recipe.html#maintainer-role)!

Of perhaps most interest: when a new version lands on PyPi , you would create a PR (even in the web UI!) that updated:
- the new [`version`](https://github.com/conda-forge/deap-feedstock/blob/master/recipe/meta.yaml#L1)
- the new [`sha256`](https://github.com/conda-forge/deap-feedstock/blob/master/recipe/meta.yaml#L3)  from [pypi.io](https://pypi.org/project/deap/#files)

Of course you could **already do this as a non-maintainer**! However, if all of the CIs pass, a maintainer can hit *Merge* and new versions would be available for everyone after the merge to `master` completes.

Because you'd only be signing up for `deap` (and not all of them), the amount of noise in your Github inbox would be minimal. On a less-than-monthly basis, you might help (i.e. press Merge!) when an automated PR comes along, usually minor changes to CI that, if they work, won't require anything more than a cursory inspection of the build logs.

Maintainers that actually make use of the package of interest are very valuable, as they are most likely to a) want the newest, shiniest features and b) know when Something Is Wrong.

Of course, the Secret Master Plan is starting with a little maintaining, you'd be driven to want to 
- learn more about `conda`, `conda-build` and `conda-forge`
- submit, improve, or maintain other feedstocks
- generally make `conda-forge` a more lovely way to get work done.

Anyhow, we waited 2.5 years between 1.0.2 and 1.2.x, so it's not like maintaining this package has been a crushing burden, but we're always looking for new, excited people!

Cheers!

**Pull request merged**
